baseURL = "https://ssiyad.com/"
languageCode = "en-us"
title = "Sabu Siyad"
theme = "vex"
copyright = "foofoo"

[params]
title = "表"
description = "ssiyad's personal website"
home = [
    ["Blog", "/blog/"],
    ["GitHub", "https://github.com/ssiyad"],
    ["PGP", "/pgp"],
    ["Donate", "https://www.buymeacoffee.com/ssiyad"],
    ["Contact", "/contact/"],
]

[author]
name = "Sabu Siyad"
email = "hello@ssiyad.com"
