baseURL = "https://ssiyad.com/"
languageCode = "en-us"
title = "ssiyad"
theme = "vex"
copyright = "foofoo"

[params]
title = "表"
home = [
    ["blog", "/blog/"],
    ["github", "https://github.com/ssiyad"],
    ["pgp", "/pgp"],
    ["donate", "https://www.buymeacoffee.com/ssiyad"],
    ["contact", "/contact/"],
]

[author]
name = "Sabu Siyad"
email = "ssiyad@disroot.org"
