name: Build and deploy GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --global --add safe.directory /github/workspace
      - name: build_css
        run: |
          cd themes/boring
          yarn install --frozen-lockfile
          yarn build
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

